getyoti/yoti-doc-scan-android

README.md, app/build.gradle
Update Yoti Doc Scan to version 1.1.1
Allow user to do Liveness and Face Matching with Yoti Doc Scan v1.1.1
=> [DEP-108] Update to yoti-doc-scan 1.1.1

README.md
Update readme file with the Proguard rules that have to be implemented by the SDK integrator. 
JIRA: [YD-1100](https://lampkicking.atlassian.net/browse/YD-1100)
=> [YD-1100] Add Proguard rules to readme

README.md, app/build.gradle
Upgrade to Yoti Doc Scan v1.1.2
=> [DEP-110] Upgrade to 1.1.2

README.md, app/build.gradle
=> [DEP-113] Update to version 1.1.3

README.md
JIRA: [YD-1333](https://lampkicking.atlassian.net/browse/YD-1333)
=> [YD-1333] Remove font customisation instructions from README

CHANGELOG.md, LICENSE.md
A CHANGELOG file has been added to show the major changes occurred in every release.
Also a LICENSE file has added to the project.
YD-1391
=> [YD-1391] Adding change log and license file.

CHANGELOG.md, README.md, app/build.gradle, app/proguard-rules-retrofit.pro, app/proguard-rules.pro, app/src/main/java/com/yoti/mobile/android/sdk/yotidocscan/sample/MainActivity.kt
Update Yoti Doc Scan to version 2.1.0
=> [DEP-125] Update to yoti-doc-scan 2.1.0

CHANGELOG.md, README.md, app/build.gradle
Update Changelog and all references.
=> Prepare for release 2.2.0

CHANGELOG.md, README.md, app/build.gradle
Set YDS SDK libraries version to 2.3.0
JIRA [DEP-149](https://lampkicking.atlassian.net/browse/DEP-149)
=> [DEP-149] Bump up YDS SDK libraries version to 2.3.0

CHANGELOG.md, README.md, app/build.gradle
JIRA [DEP-159](https://lampkicking.atlassian.net/browse/DEP-159)
Create **release build** (sign with your own key/keystore)
1. Change device TimeZone to United States (Chihuahua is cool).
2. Start document flow and read your ePassport.
3. NFC flow starts & you're able to pass it.
=> [DEP-159] Bump up android libraries version to 2.3.2

CHANGELOG.md, README.md, app/build.gradle
Related to [DEP-162](https://lampkicking.atlassian.net/browse/DEP-162)
=> [DEP-162] Bump up Yoti SDK version to 2.4.0 & add new Sup.Docs. module

CHANGELOG.md, README.md, app/build.gradle, app/src/main/java/com/yoti/mobile/android/sdk/yotidocscan/sample/MainActivity.kt
Bump up Yoti SDK libraries to 2.5.0 & Doc. update
Related to [DEP-181](https://lampkicking.atlassian.net/browse/DEP-181)
=> [DEP-181] Release 2.5.0 

CHANGELOG.md, README.md, app/build.gradle
Bump up Yoti SDK libraries to 2.5.1 & Doc. update
Related to [DEP-183](https://lampkicking.atlassian.net/browse/DEP-183)
=> [DEP-183] Release 2.5.1

webapp/src/main/java/com/yoti/mobile/android/sdk/yotidocscan/websample/MainActivity.kt
1. Start a SupDoc session
2. Tap `BROWSE`, a chooser is shown
3. Tap `Camera` or `Files`
4. The preview is shown after taking a pic by camera
=> [YD-2681] Enable camera option for Supplementary document flow in the Web View App

README.md, app/build.gradle
[YD-2640](https://lampkicking.atlassian.net/browse/YD-2640)
=> [YD-2640] Update README.md: advices about how to reduce APK size

CHANGELOG.md, README.md, app/build.gradle
- Update SDK libraries implementation
- Update README.md & CHANGELOG.md
[DEP-193](https://lampkicking.atlassian.net/browse/DEP-193)
=> [DEP-193] Bump up SDK version to 2.6.0

README.md
[YD-2853](https://lampkicking.atlassian.net/browse/YD-2853)
=> [YD-2853] Update README for 5009 - Storage Error

README.md
[YD-2359](https://lampkicking.atlassian.net/browse/YD-2359)
=> [YD-2359] Update README for open-source licensed software usages

CHANGELOG.md, README.md, app/build.gradle
By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.
Release 2.6.0
Deployment ticket: [DEP-193](https://lampkicking.atlassian.net/browse/DEP-193)
Release content: [Release 2.6.0](https://lampkicking.atlassian.net/projects/YD/versions/41637/tab/release-report-all-issues) 
@lampkicking/android-dev
=> [DEP-193] Release 2.6.0

CHANGELOG.md, README.md, app/build.gradle
SDK Release 2.9.0
[DEP-294](https://lampkicking.atlassian.net/browse/DEP-294)
=> [DEP-294] Release 2.9.0

CHANGELOG.md, README.md, app/build.gradle
SDK Release 2.9.1
[DEP-317](https://lampkicking.atlassian.net/browse/DEP-317)
=> [DEP-317] Release 2.9.1

CHANGELOG.md, README.md, app/build.gradle
SDK Release 2.9.2
[DEP-325](https://lampkicking.atlassian.net/browse/DEP-325)
=> Release 2.9.2 - Bump up SDK version to 2.9.2

CHANGELOG.md, README.md, app/build.gradle
SDK Release 2.9.1
[DEP-327](https://lampkicking.atlassian.net/browse/DEP-327)
[DEP-327]: https://lampkicking.atlassian.net/browse/DEP-327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEP-327] Release 2.9.3

CHANGELOG.md, README.md, app/build.gradle, app/proguard-rules.pro, build.gradle
SDK Release 3.0.0
- Update Kotlin version
[DEP-339](https://lampkicking.atlassian.net/browse/DEP-339)
[DEP-339]: https://lampkicking.atlassian.net/browse/DEP-339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEP-339] Release 3.0.0

CHANGELOG.md, README.md, app/build.gradle
SDK Release 3.0.1
[DEP-379](https://lampkicking.atlassian.net/browse/DEP-379)
[DEP-379]: https://lampkicking.atlassian.net/browse/DEP-379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEP-379] Release 3.0.1

CHANGELOG.md, README.md, app/build.gradle
SDK Release 3.1.0
[DEP-390](https://lampkicking.atlassian.net/browse/DEP-390)
[DEP-390]: https://lampkicking.atlassian.net/browse/DEP-390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEP-390] Release 3.1.0

CHANGELOG.md, README.md, app/build.gradle
SDK Release 3.1.1
[DEP-399](https://lampkicking.atlassian.net/browse/DEP-399)
[DEP-339]: https://lampkicking.atlassian.net/browse/DEP-339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEP-399]: https://lampkicking.atlassian.net/browse/DEP-399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEP-399] Release 3.1.1

CHANGELOG.md, README.md, app/build.gradle
SDK Release 3.2.0
[DEP-424](https://lampkicking.atlassian.net/browse/DEP-424)
[DEP-424]: https://lampkicking.atlassian.net/browse/DEP-424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEP-424] Release 3.2.0

CHANGELOG.md, README.md, app/build.gradle
SDK Release 3.2.1
[DEP-435](https://lampkicking.atlassian.net/browse/DEP-435)
[DEP-435]: https://lampkicking.atlassian.net/browse/DEP-435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEP-435] Release 3.2.1

CHANGELOG.md, README.md, app/build.gradle
SDK Release 3.2.2
[DEP-452](https://lampkicking.atlassian.net/browse/DEP-452)
[DEP-452]: https://lampkicking.atlassian.net/browse/DEP-452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEP-452] Release 3.2.2

CHANGELOG.md, README.md, app/build.gradle, build.gradle, gradle/wrapper/gradle-wrapper.properties
SDK Release 3.3.0
- Update compile and target SDK versions
- Update AGP version
- Update `README.md` and `CHANGELOG.md`
[DEP-490](https://lampkicking.atlassian.net/browse/DEP-490)
[DEP-424]: https://lampkicking.atlassian.net/browse/DEP-424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEP-490]: https://lampkicking.atlassian.net/browse/DEP-490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEP-490] Release 3.3.0

CHANGELOG.md, README.md, app/build.gradle, build.gradle
SDK Release 3.4.0
- Bump up SDK version to 3.4.0
[DEP-519](https://lampkicking.atlassian.net/browse/DEP-519)
[DEP-519]: https://lampkicking.atlassian.net/browse/DEP-519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEP-519] Release 3.4.0

CHANGELOG.md, README.md, app/build.gradle
SDK Release 3.5.0
[DEP-535](https://lampkicking.atlassian.net/browse/DEP-535)
[DEP-535]: https://lampkicking.atlassian.net/browse/DEP-535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEP-535] Release 3.5.0

CHANGELOG.md, README.md, app/build.gradle
SDK Release 3.5.1
- Upgrade SDK libraries version to 3.5.1
- Update CHANGELOG to include main features included in this release.
- Update README.md with references to the latest version
[DEP-546](https://lampkicking.atlassian.net/browse/DEP-546)
[DEP-546]: https://lampkicking.atlassian.net/browse/DEP-546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEP-546] Release 3.5.1

CHANGELOG.md, README.md, app/build.gradle
SDK Release 3.5.2
- Upgrade SDK libraries version to 3.5.2
- Update CHANGELOG to include main features included in this release.
- Update README.md with references to the latest version
[DEP-546](https://lampkicking.atlassian.net/browse/DEP-546)
[DEP-546]: https://lampkicking.atlassian.net/browse/DEP-546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEP-564] Release v3.5.2

CHANGELOG.md, README.md, app/build.gradle, app/proguard-rules.pro, app/src/main/AndroidManifest.xml, build.gradle, gradle/wrapper/gradle-wrapper.properties, webapp/build.gradle, webapp/src/main/AndroidManifest.xml, webapp/src/main/java/com/yoti/mobile/android/sdk/yotidocscan/websample/MainActivity.kt
SDK Release 4.0.0
- Update SDK libraries and address small breaking change
- Update demo app AGP to latest version and fix compatibility issues
[DEP-571](https://lampkicking.atlassian.net/browse/DEP-571)
[DEP-535]: https://lampkicking.atlassian.net/browse/DEP-535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEP-571]: https://lampkicking.atlassian.net/browse/DEP-571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEP-571] Release 4.0.0

README.md
The links to the developer docs in the README were broken and this PR updates them to the correct ones.
Project README file.
@lampkicking/android-dev
=> [TASK][YD-7064] Update README
